# config for target conditioned experiments with image obs

_target_: diffusion_policy.workspace.train_binary_classifier_workspace.TrainBinaryClassifierWorkspace
name: embedding_classification
dataloader:
  batch_size: 256
  num_workers: 8
  persistent_workers: false
  pin_memory: true
optimizer:
  _target_: torch.optim.AdamW
  betas:
  - 0.95
  - 0.999
  eps: 1.0e-08
  lr: 0.0001
  weight_decay: 1.0e-06
model:
  _target_: diffusion_policy.model.classification.binary_classifier.BinaryClassifier
  input_dim: 20
  layer_sizes: []
dataset:
  _target_: diffusion_policy.dataset.binary_classification_dataset.BinaryClassificationDataset
  data_0_path: "/home/adam/workspace/gcs-diffusion/data/experiments/cotrain/scaled_mixing/10_2000/seed_0/real_embeddings.npy"
  data_1_path: "/home/adam/workspace/gcs-diffusion/data/experiments/cotrain/scaled_mixing/10_2000/seed_0/sim_embeddings.npy"
val_split: 0.2
training:
  device: cuda
  num_epochs: 20
  seed: 42