# config for target conditioned experiments

_target_: diffusion_policy.workspace.train_diffusion_unet_lowdim_workspace_no_env.TrainDiffusionUnetLowdimWorkspaceNoEnv
action_dim: 2
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-val_loss={val_loss:.3f}.ckpt
    k: 5
    mode: min
    monitor_key: val_loss
dataloader:
  batch_size: 256
  num_workers: 1
  persistent_workers: false
  pin_memory: true
  shuffle: true
ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0
exp_name: default
horizon: 16
logging:
  group: null
  id: null
  mode: online
  name: train_diffusion_unet_lowdim_maze_target_conditioned
  project: diffusion_policy_target_conditioned
  resume: true
  tags:
  - train_diffusion_unet_lowdim_target_conditioned
  - maze_lowdim
  - default
multi_run:
  run_dir: data/outputs/2024.01.16/train_diffusion_unet_lowdim_maze_target_conditioned
  wandb_name_base: train_diffusion_unet_lowdim_maze_target_conditioned
n_action_steps: 8
n_latency_steps: 0
n_obs_steps: 4
name: train_diffusion_unet_lowdim
obs_as_global_cond: true
obs_as_local_cond: false
obs_dim: 2
optimizer:
  _target_: torch.optim.AdamW
  betas:
  - 0.95
  - 0.999
  eps: 1.0e-08
  lr: 0.0001
  weight_decay: 1.0e-06
past_action_visible: false
policy:
  _target_: diffusion_policy.policy.diffusion_unet_lowdim_policy.DiffusionUnetLowdimPolicy
  obs_dim: 2
  action_dim: 2
  target_dim: 2
  horizon: 16
  model:
    _target_: diffusion_policy.model.diffusion.conditional_unet1d.ConditionalUnet1D
    cond_predict_scale: true
    diffusion_step_embed_dim: 64
    down_dims:
    - 64
    - 128
    - 256
    global_cond_dim: 8 # 4*2 dim for obs history
    target_cond_dim: 2 # 2 dim for target
    input_dim: 2
    kernel_size: 3
    local_cond_dim: null
    n_groups: 8
  n_action_steps: 8
  n_obs_steps: 4
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    beta_start: 0.0001
    clip_sample: true
    num_train_timesteps: 100
    prediction_type: epsilon
    variance_type: fixed_small
  num_inference_steps: 100
  oa_step_convention: true # keep true
  obs_as_global_cond: true # keep true
  obs_as_local_cond: false # keep false
  use_target_cond: true # must be true for this experiment
  pred_action_steps_only: false
pred_action_steps_only: false
task:
  action_dim: 2
  dataset:
    _target_: diffusion_policy.dataset.drake_maze_target_conditioned_dataset.MazeLowdimTargetConditionedDataset
    horizon: 16
    max_train_episodes: null # I think this caps the number of training episodes
    pad_after: 7
    pad_before: 3
    seed: 42
    val_ratio: 0.1
    # Override if using smaller dataset
    # ex. task.dataset.zarr_path=data/maze/maze_dataset_target_conditioned_100.zarr
    zarr_path: data/maze/maze_dataset_target_conditioned.zarr
  name: maze_lowdim_target_conditioned
  obs_dim: 2
task_name: maze_lowdim_target_conditioned
training:
  checkpoint_every: 5
  debug: false
  # device: cuda:0
  device: cpu
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 500
  max_train_steps: null
  max_val_steps: null
  num_epochs: 100
  resume: true
  rollout_every: 5
  sample_every: 5
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 1
val_dataloader:
  batch_size: 256
  num_workers: 1
  persistent_workers: false
  pin_memory: true
  shuffle: false